spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: none
        default_schema: work_office
    show-sql: true
  sql:
    init:
      mode: always
      continue-on-error: true
  database:
    driverClassName: org.postgresql.Driver
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: username
    password: password
